title:            The Flying Developer
description:      My ongoing adventures
url:              http://theflyingdeveloper.com
signoff:          David

links:
  - name:         Home
    url:          /
  - name:         About Me
    url:          /about

permalink:        :title
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
