title:            The Flying Developer
description:      My ongoing adventures
url:              http://theflyingdeveloper.com
signoff:          David
disqus_shortname: theflyingdeveloper
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-37972623-1

links:
  - name:         Twitter
    url:          http://twitter.com/davefp
  - name:         GitHub
    url:          http://github.com/davefp
  - name:         Contact
    url:          mailto:david@theflyingdeveloper.com

permalink:        :title
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
